### ISSUE TITLE
Feature Request - Revert Master Record listing to old style

### ISSUE THREAD

**Issue by negative1ne** [salcido/discogs-enhancer#191] opened 2022-09-24 18:33 UTC
The New UI upgrade has made it harder to look through all the versions at once.

Now for large listings, you have to press more, to get each section to load.

<img width="632" alt="simpNGver" src="https://user-images.githubusercontent.com/76970606/192113372-ad3401fc-270a-4562-91d4-baba776655fe.PNG">

The old listing style is still viewable, when you go to edit a release, or just click on versions.
<img width="823" alt="simpNGverList" src="https://user-images.githubusercontent.com/76970606/192113419-a72a43ca-e3ec-44b5-b4cd-884d7191713d.PNG">

Maybe there's a way to reimport that data, and then give the usual dropdowns for sorting by year, country, format, etc.

later
-1

**Comment by salcido** [comment] 2022-09-26 15:55
@negative1ne So the issue is that you want to be able to see all the releases on the MR page without having to click `Show more versions...` - is that right? 

I'm mostly a 12" singles collector so I don't use the MR page often, sorry!

**Comment by negative1ne** [comment] 2022-09-26 17:26
> @negative1ne So the issue is that you want to be able to see all the releases on the MR page without having to click `Show more versions...` - is that right?
> 
> I'm mostly a 12" singles collector so I don't use the MR page often, sorry!


Hi Mr. Salcido, yes, that is correct. I do like 12 inches also (and have several hundred).

But for albums that have hundreds of versions, its hard to compare all the formats.

Even for 12 inch singles, they are huge. Try : New Order - Blue Monday
https://www.discogs.com/master/3297-New-Order-Blue-Monday

I collect multiple formats too. And sometimes I like to see all the countries,
and compare.

Do you think its possible. The code for the old format is there, but not
the sorting filters.

later
-1

**Comment by salcido** [comment] 2022-09-27 18:01
@negative1ne Ok thanks! I'll take a look and see what can be done. I can't say that I can fix things but I might be able to at least make it a little easier to deal with. Thanks for taking the time to open up an issue. I really appreciate it!

**Comment by salcido** [comment] 2023-04-07 18:01
Closing this ticket since Discogs has updated things to show all versions.

**Closed by salcido** 2023-04-07 18:01 UTC
Labels: feature

**Comment by negative1ne** [comment] 2023-04-07 22:37
hi matthew,

thanks for looking into it.
but nothing has changed.

the problem is still there.

before, when you looked at a release.
you could see every listing and version of it.

now you cant. yes, they added some filters.
but try to copy and paste from the list. you can't.

before you would get the entire listing, you could
copy and paste the list into a spreadsheet, and now you can't.

if you want to see the operation, go to any artist. go to
the section (album, single, etc), and click on the versions there.

you can see a minimal listing, that you can copy and paste from,
but its still not complete.

thanks
raj


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by salcido** [comment] 2023-04-07 22:51
The ask for this was to show all versions of a release. Previously, you had to click `Show More Versions` multiple times in order to see every version in the Master Release. 

That button updated to show `all versions` with a single click which sounded like it satisfies the request you had made. 

```
The New UI upgrade has made it harder to look through all the versions at once.

Now for large listings, you have to press more, to get each section to load.
```

So this is why I closed the ticket.

What you're asking for now is different from what you asked initially. Sounds like now you want the ability to copy and paste the content of a master release into a spread sheet. I'm not sure I can help with that.

**Comment by negative1ne** [comment] 2023-04-07 23:34
hi  matthew,

i agree, the see all versions does help.
you're right you can see them all now.

i guess i should have specified why i wanted to show all versions.

the point was to be able to see all the versions so that you
could capture the information, and manipulate it the way
you wanted to (by copy paste)

they removed that functionality, so now it is view only.
-----
the reason i pointed out the old method, is they still
have it implemented in their scripting, when you click
in the major areas listing as i showed.

so what i was asking for was that functionality to see all,
and to be able to capture that information.

instead of only having it as a view only.
---
on the main releases page, you click on the toggle button.

like - new order - temptation [20 versions] <- once you click on this toggle

<button class="mr_toggler button button-white button-short" aria-label="Hide 20 versions" data-show-text="Show 20 versions" data-hide-text="Hide 20 versions">
            <i role="img" aria-hidden="true" class="icon icon-caret-down"></i>
            20  versions  </button>

this leads to :
<tr class="card r_tr r7028399 sub release             shortcut_navigable sub_first" data-id="r7028399" data-object-id="7028399" data-object-type="release" data-master-id="41074" data-parent-group-url="/master/41074/versions/artist/3909?noanv=False&amp;sort=year&amp;sort_order=asc" id="r7028399">
                <td class="status hide_mobile">

this script, would then cycle through all the listings to populate the table.

i was hoping that this script could be incorporated on the page with
the new release listing.

perhaps not.

thanks
raj



Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by salcido** [comment] 2023-04-08 17:06
Ah, I see what you're saying. I'll take a look but I'm not sure how long that endpoint is going to continue to work.
